export const SCREENS = {
    BOTTOM_TAB_SCREEN: 'BOTTOM_TAB_SCREEN',
    POST_TAB_SCREEN: 'POST_TAB_SCREEN',
    PHOTO_TAB_SCREEN: 'PHOTO_TAB_SCREEN',
    HOME_TAB_SCREEN: 'HOME_TAB_SCREEN',
    MENU_TAB_SCREEN: 'MENU_TAB_SCREEN',
    SHOPPING_CARD_TAB_SCREEN: 'SHOPPING_CARD_TAB_SCREEN',
    REWARD_TAB_SCREEN: 'REWARD_TAB_SCREEN',
    ACCOUNT_TAB_SCREEN: 'ACCOUNT_TAB_SCREEN',

    POST_SCREEN: 'PostScreen',
    POST_DETAIL_SCREEN: 'PostDetailScreen',
    PHOTO_SCREEN: 'PhotoScreen',
    PHOTO_DETAIL_SCREEN: 'PhotoDetailScreen',
    HOME_SCREEN: 'HomeScreen',
    MENU_SCREEN: 'MenuScreen',
    CART_SCREEN: 'CartScreen',
    REWARD_SCREEN: 'RewardScreen',
    PROFILE_SCREEN: 'ProfileScreen',

    SPLASH_SCREEN: 'SplashScreen',
    POKEMON_LIST_SCREEN: 'PokemonListScreen',
    POKEMON_DETAIL_SCREEN: 'PokemonDetailScreen',
};
